### PR TITLE
New version with RecyclerView and Firebase

### PR DESCRIPTION
**Pull request by redlor**
Have a look please and let me know if you find it suitable. Thank you.

Changes:
	Added a confirmation dialog when the button to delete all the checked items is pressed. The confirmation dialog is retained during orientation change. Since we are deleting all the items at once, better asking for a confirmation from the user.
•	Switched from ListView to RecyclerView. Implemented a new adapter for a RecyclerView which contains two interfaces for click and long click listeners (this one do nothing but can be implemented, for example by showing the current reminder date and time). In addition, implemented the logic when an item is checked the item on Firebase Database update with the new value. Created a custom divider line for the RecyclerView.
•	Implemented Dual Pane mode. When on a tablet, the detail fragment is shown on the side of the MainActivity and it is updated at runtime when the user clicks on an item. To achieve that, a new Activity and a Fragment have been created, along with a xml file in a dedicated folder with a LinearLayout that is checked in the MainActivity. If it is not null, we are in dual pane and the fragment is added, otherwise we are on a phone and the app runs as it was before. I added a screenshot in the Photo folder.
•	Started Firebase implementation, along with SQLite. Even if Firebase allows to store data locally, it was such a big change, so SQLite still stores the data. The local database has been changed to store also the Id assigned to the item by Firebase, in order to make operation on items based on its id (initially I did by name, but then I noticed that items with the same name were removed both). Firebase needs still some implementation, like checking the Internet connection, authentication, etc., but it requires more time.

Regards,

Lorenzo

### CODE REVIEW

**Comment by luong-komorebi** [comment]
@redlor  Hi there. First of all, I must say that I'm impressed. 
1. I made this project for training purpose in the past, after I learnt Android 😄 Never thought it could receive such high quality contribution like this.
2. This pull request is decent in both idea and implementation. Thank you so much 👍 
However, I wont merge in these changes. 
----------
It is not because it is bad or it conflicts with my view or something. I am now just too busy to maintain this project. I would be happy that you make a fork of it and continue to maintain development. I would put a link here in the readme that links to your repo. How does that sound to you? Also, if you are interested in putting it on the PlayStore,  I would be happy to pull mine off for you.

**Comment by redlor** [comment]
Hello @LewisVo ,

thank you for your reply. I am glad you liked my code. 
Definitely I can find some time to maintain and develop the project, along with others I am involved at the moment. For sure, go on will be good for me to do some experience and practice.
So yes, if you want, insert a link to the forked repo:

https://github.com/redlor/Minitask

There is still some things I would improve on it, maybe I can also find someone who wants to contribute,  it would be great!
I have to thank you, I was not expecting this, you did very a good job, the design is clear and simple, as every app of this kind should be. About publishing on the Play Store, I can think about that after finishing the Firebase part, I will let you know obviously if I decide to publish it.
Have a nice evening!
Regards,

Lorenzo

**Comment by luong-komorebi** [comment]
> I have to thank you, I was not expecting this, you did very a good job, the design is clear and simple, as every app of this kind should be.   

Thank you, this is so motivative.      😄 

> About publishing on the Play Store, I can think about that after finishing the Firebase part, I will let you know obviously if I decide to publish it.    

Yeah, any time.  This is an open source project, you don't have to spend all your workday for it.  If you publish an updated version on Playstore, the benefits go towards users the most 😄   
Also, I am making another app, would post it here if you'd like to hear about. 👍

**Comment by redlor** [comment]
@LewisVo 
thank you for the link. I opened the issue page and will start to post some enhancements and see if anyone will collaborate. I will dedicate some time when I can.

> Yeah, any time. This is an open source project, you don't have to spend all your workday for it. If you publish an updated version on Playstore, the benefits go towards users the most 😄
> Also, I am making another app, would post it here if you'd like to hear about. 👍

Great, good luck with the implementation, I will be for sure around  to see it!

**Comment by redlor** [comment]
@LewisVo 
I am working on the project but really far away to be finished...
in the meantime, I saw you credited for the icons:
https://www.flaticon.com/free-icon/startup_341435#term=rocket&page=2&position=33
https://www.flaticon.com/free-icon/rocket_122111#term=rocket&page=2&position=62

any other credit should be added for images and other icons?
Let me know when you have time please.

thank you :)

**Comment by luong-komorebi** [comment]
@redlor  I am concerned with credits and I give credits where credits are due. In my app, I can only find the credit for the icon. Other things such as the header images are available on the internet (free to use - CC BY-SA). I only resize them and use ;)

**Comment by redlor** [comment]
Thank you for replying! I didn't touch the layout at all, so that credits should be enough.

**Comment by redlor** [comment]
@LewisVo hello! I am starting some tests to publish the app but I noticed that an old version of the app is already on the Play Store. Do you plan to keep it there or you can remove it? Let me know if I should change the app name and all the rest or I can publish this one. Obviously me and you are in the About page of the app. Thank you!

**Comment by luong-komorebi** [comment]
Hi @redlor , it's nice to see you again.
I have some suggestions for you:   
~~1. I will add you to the play console of the current app and let you manage everything. This is done via https://support.google.com/googleplay/android-developer/answer/2528691?hl=en . This has the benefit that we don't have to take down any app and your changes are published as an update to the current app.~~

2. Of course, if you are not satisfied with the solution above, just be honest and tell me. I am ready to take my app down at any time for yours to be on the playstore listing 😄 . I myself also prefer this.   

 Update: I chose option 2. I will take down my app now ;) When your app is released on the play store, please notify me as I am very glad to see it evolve 🛩

**Comment by redlor** [comment]
Hi @LewisVo !!!
I already added a version on myCcnsole for Alpha Testing and set up almost everything, even got some friends that will test it for me :)
So it would be easier for me to start with a new publish. Since you also prefer the solution 2, I think it is the most applicable. Let me know please .
And obviously if you want to be among the testers, I would be very honored.

Many thanks!!

**Comment by luong-komorebi** [comment]
Hi @redlor , I have unpublished the app on the Play Store. It would take sometimes for this to take effect as of right now https://play.google.com/store/apps/details?id=luongvo.com.todolistminimal is still available.  Here is a proof : 
image
   
I wish you success for the update of my app. ;)

**Pull request closed without merging**
